apiVersion: v1
kind: Service
metadata:
  name: {{ include "bpa.fullname" . }}
  labels:
    {{- include "bpa.labels" . | nindent 4 }}
spec:
  type: {{ .Values.bpa.service.type }}
{{- if .Values.bpa.service.clusterIP }}
  clusterIP: {{ .Values.bpa.service.clusterIP }}
{{- end }}
  ports:
    - port: {{ .Values.bpa.service.port }}
      targetPort: {{ .Values.micronaut.server.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "bpa.selectorLabels" . | nindent 4 }}
