apiVersion: v1
kind: Secret
metadata:
  name: {{ template "bpa.fullname" . }}
  labels:
    app: {{ template "global.name" . }}
    chart: {{ template "global.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  postgresql-password: {{ .Values.bpa.db.password | b64enc | quote }}
